---
- name: First play
  strategy: free
  hosts: example
  tasks:
    - name: Ping it
      ping:
    - name: Print Hello world!
      debug:
        msg: Hello world!
- name: Second play
  strategy: linear
  serial: 4
  hosts: example
  tasks:
    - name: Ping it
      ping:
    - name: Print Bye world!
      debug:
        msg: Bye world!
